version: "3.8"
services:
  postgres:
    container_name: nine-rush-postgres
    image: postgres:13.0-alpine
    volumes:
      - nine-rush-postgres:/var/lib/postgresql/
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - nine-rush-network
  pgadmin:
    container_name: nine-rush-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5430:80"
    networks:
      - nine-rush-network
networks:
  nine-rush-network:
    name: "nine-rush-network"
    driver: bridge
volumes:
  nine-rush-postgres:

