version: "3.8"
services:
  postgres:
    container_name: nine-rush-postgres
    image: postgres:13.0-alpine
    volumes:
      - nine-rush-postgres:/var/lib/postgresql/
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - nine-rush-network
networks:
  nine-rush-network:
    driver: bridge
volumes:
  nine-rush-postgres:
  nine-rush-pgadmin-data:

